### PR TITLE
Support Vue 3

### PR DESCRIPTION
**Pull request by Alexeykhr**
https://github.com/Alexeykhr/vue-stripe-menu/issues/196

### CODE REVIEW

**Comment by amirhossein95b** [comment]
How do I build a library (project | plugin)? When I build, it gives the error that raw-loader and sass-loader are needed. I have installed these two. But it still gives an error. What should I do?

**Comment by Alexeykhr** [comment]
Can you show me this error?

**Comment by amirhossein95b** [comment]
> Can you show me this error?

image

**Comment by amirhossein95b** [comment]
> Can you show me this error?

image

**Comment by Alexeykhr** [comment]
So, I'm on the PC, let's look at the problem.

To run this repository, you need:
Node: v15.3.0 (14 should be fine too)

Run:
- `$ yarn`
- `$ yarn test`

**Comment by Alexeykhr** [comment]
Yes, you will need to somehow normally make this repository, demolish these sass settings (forward through css `--variables`), write normal code, various css stubs, oh ..: D

**Pull request merged**
